const CarrerConstants = {
    CREATE_TAB: 'CREATE_TAB',
    INIT_BUTTONS_VALUES: 'INIT_BUTTONS_VALUES',
    LOAD_BUTTON_VALUES: 'LOAD_BUTTON_VALUES',
    BACK_BUTTONS_VALUES: 'BACK_BUTTONS_VALUES',
    SET_ACTIVE_TAB_BY_ID: 'SET_ACTIVE_TAB_BY_ID',
    OPEN_BUTTON: 'OPEN_BUTTON',
}

export default CarrerConstants; 